### ISSUE TITLE
Question: OpenFaaS triggers in .NET

### ISSUE THREAD

**Issue by ChristianWeyer** [redpandaltd/faas-aspnet-template#2]
Hi - and thanks a lot for a great library.

Wanted to ask you whether you have experience in using triggers (like the MQTT trigger) in OpenFaaS with .NET/C#?

Thanks.

**Comment by goncalo-oliveira** [comment]
Hi @ChristianWeyer ,

Thanks for the comment! I appreciate it!

There's an OpenFaaS [connector for MQTT](https://github.com/openfaas/mqtt-connector), don't know if you already stopped there. That's one possibility and possibly the most direct route.

Depending on your resources/requirements, maybe you want to have a look at [CloudEvents](https://cloudevents.io/) instead. There's a [MQTT spec](https://github.com/cloudevents/spec/blob/v1.0.1/mqtt-protocol-binding.md) for it as well. You can check [John's demo](https://github.com/johnmccabe/cloudevents-slack-demo) with CloudEvents and Azure's EventGrid.

Hope this helps!

**Comment by goncalo-oliveira** [comment]
See also [CloudEvents SDK](https://github.com/cloudevents/sdk-csharp) for .NET.

**Comment by ChristianWeyer** [comment]
Thanks!
