### ISSUE TITLE
Adding Unit/Integration Test Throws System.InvalidOperation Exception 

### ISSUE THREAD

**Issue by YaredDejene** [redpandaltd/faas-aspnet-template#4]
I am trying to add a test project to a OpenFaas function which is based on this template. I have tried to follow the basic steps to add a test project for ASP.NET Core 6 web application. But I ended up getting `System.InvalidOperation` exception.

Steps to reproduce the issue:

**1. Create function together with the test project** 
```
mkdir testing_aspnet
cd testing_aspnet
faas-cli template pull https://github.com/goncalo-oliveira/faas-aspnet-template
faas-cli new --lang aspnet aspnet1 
dotnet new xunit -o test1
```
**2. Function project** 
Add the following line of code at the end of `Program.cs` hence we can instantiate it the class from the test project.
```
public partial class Program { }
```

**3. Test project**
Add a reference to `aspnet1` project and the `Microsoft.AspNetCore.Mvc.Testing` package to the test project. Change the `UnitTest1.cs` class as show below: 

```
using Microsoft.AspNetCore.Mvc.Testing;
using Xunit;

namespace test1;

public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        using var app = new WebApplicationFactory<Program>();
        using var client = app.CreateClient();
    }
}
```
4. Running `dotnet test` command from the test project's directory results the following exception:

> [xUnit.net 00:00:01.00]     test1.UnitTest1.Test1 [FAIL]
>   Failed test1.UnitTest1.Test1 [112 ms]
>   Error Message:
>    System.InvalidOperationException : The entry point exited without ever building an IHost.
>   Stack Trace:
>      at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
>    at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
>    at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
>    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()

Any help is appreciated,
Thanks

**Comment by goncalo-oliveira** [comment]
Hi @YaredDejene,

I've managed to replicate the issue and I have found the root cause for it. I'll handle this as soon as I can and publish an update.

Just a quick note: You actually don't need to add the `partial class Program` if you specify in code or in the project that internals are visible to the test project. For example, in the project file

```xml
  <ItemGroup>
    <InternalsVisibleTo Include ="test1"/>
  </ItemGroup>
```

**Comment by goncalo-oliveira** [comment]
@YaredDejene 

I've published a new version of the runner library to address this issue. When running through the test host, additional arguments were being passed and the parser was failing because it didn't recognize them. I addressed this to ignore any unknown arguments and I also fixed an issue with the urls when running through the test host.

Just update the runner package on your function `.csproj` and you should be fine. No need to update the template.

```xml
      <PackageReference Include="OpenFaaS.Runner" Version="2.0.2" />
```

**Comment by YaredDejene** [comment]
Hi @goncalo-oliveira ,

Thanks for the quick fix. Version 2.0.2 of the runner library works fine now.

**Comment by goncalo-oliveira** [comment]
I need to point out that the latest version of the runner (2.0.2) raised a new [issue](https://github.com/goncalo-oliveira/faas-aspnet-runner/issues/1). This is an ASPNET bug and the workaround for it has been applied to the template. If you are seeing the upstream error, you just need to update the template and rebuild the image. The runner library remains unchanged (2.0.2).

```
faas-cli template pull https://github.com/goncalo-oliveira/faas-aspnet-template --overwrite
```

Hope this helps!
