### ISSUE TITLE
Runtime Instance

### ISSUE THREAD

**Issue by Zetanova** [redpandaltd/faas-aspnet-template#5]
It is not clear for me after reading the documentation:
Is OpenFaaS starting a single instance for each function or does the whatchdog starts it?
Is a single instance of this aspnet-fn reused multiple times or restarted after every request?

I am asking because I know that kestrel is relatively slow to start and relatively memory hungry.
To process only a single request OR to start 100 kestrels for 100 different functions 
will consume a lot of resources.

**Comment by Zetanova** [comment]
I found the answer, it will create a single instance and use it:
https://docs.openfaas.com/architecture/watchdog/

It makes a spectate container for each single function with c# over kestrel not practical 
on higher function count with low request frequency

**Comment by goncalo-oliveira** [comment]
@Zetanova the watchdog is essentially just a proxy embedded with the function; it functions as a monitoring tool for OpenFaaS (so it knows it's responding and when to scale) and upstreams the requests to the function itself (Kestrel by default).

The warm up is something known in the ASPNET world and can indeed add some delay to the first request. However, this has been greatly improved in the latest versions. This template in particular, makes use of minimal APIs which uses Kestrel with the minimal load possible to reduce that warm up time.

In the OpenFaaS context, it is only an issue if you are using [scale-to-zero](https://docs.openfaas.com/openfaas-pro/scale-to-zero/). If that's not the case, then it's just the first request that will require a warm up which you could circumvent when deploying by making a "startup" request.

> It makes a spectate container for each single function with c# over kestrel not practical
on higher function count with low request frequency

I'm unsure what you mean by this, but it seems that you think that a container is created for each request, which is not the case.

**Comment by Zetanova** [comment]
I mean that if you have many (>100) separate functions/images all using kestrel,
then all 100 instances would be created and started, even when there is **no single request for days**. 

It would coast relatively much memory.

**Comment by Zetanova** [comment]
scale-to-zero will work of course and using kestrel as microservice 
I already requested a "call" at https://www.openfaas.com/support/

**Comment by goncalo-oliveira** [comment]
> then all 100 instances would be created and started, even when there is no single request for days

Yes, that is true... even considering if you only have one instance per function, you'd have 100 containers running, true. Though, that's not a dotnet issue, but how OpenFaaS works.

> scale-to-zero will work of course and using kestrel as microservice

Agreed. This will solve, as you'll be able to spin up the function container only when needed. The downside is that you'll get a slight performance hit with the first request (warm up).

> I already requested a "call" at https://www.openfaas.com/support/

That is a good idea, though, be prepared as the PRO version of OpenFaaS isn't cheap... at all...

A good alternative to OpenFaaS could be [Knative](https://knative.dev/docs/serving/autoscaling/scale-to-zero/); it also supports scale-to-zero. OpenFaaS is easier to start, for sure, but I've been finding Knative much more flexible. There's plenty of documentation available and a community to help, which with OpenFaas might not be always the case.

Good luck!

**Comment by Zetanova** [comment]
Knative is already to much/big, I think, 

I am interested in the async-webhook callback and the monitoring feature of openFaaS.
To decuple simple and sparse executions like for reports, emails requests and maybe for a k8s admission controller

It makes somehow little sens to use openFaaS even for a raspberry without an on-demand startup.

One idea that I have and don't know fully if its working, 
would be to create an base image with the full app binaries and the `System.CommandLine.Hosting`
and then simply to use it for each function with different command line argument over the fork method. 
The draw back would be 
1) each function would still get a watchdog-pod, kubernetes does not support unlimited pods per node, 
the count is very low (~110)
2) memory caching is not present

One other would be to push all received requests to a NATS JetStream Queue (with or without reply feature)
and let a NATS monitor watch the queue for all new messages and on each message it could scale/register 
the worker pod. The worker pod could dequeue the work items and reply over the NATS-reply feature.

But yes to much work and all over engineered

**Comment by goncalo-oliveira** [comment]
> Knative is already to much/big, I think,

I thought as much, but it really isn't. It's just a bit harder to understand at first. As I said, OpenFaaS has an easier learning curve/starting point, where as Knative requires some reading.

> I am interested in the async-webhook callback and the monitoring feature of openFaaS.
To decuple simple and sparse executions like for reports, emails requests and maybe for a k8s admission controller

OpenFaaS can be a good solution for simple things like this. I do use it for similar scenarios like the ones you described, but I don't have +100 different functions. I might have +20 instances of a single function at some point, depending on the workload, but when idle, there's always an idle container running. For scenarios where we do have concerns on idle cost, we've moved to Knative; it offers same/more complete functionality at a fraction of the cost of OpenFaaS PRO.

> But yes to much work and all over engineered

Know very much how that feels like and... would advise to attempt to simplify it, as it will bite you in the long run.

Best of luck!
